### ISSUE TITLE
NullPointerException at "models.Hit" cancels query session

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid#173]
Trying to load the nwbibset using [SampleUsage.java](https://github.com/hbz/lobid/blob/master/test/tests/SampleUsage.java) to get the whole NWBib set sometimes break with this error :
    2015-06-19 10:18:46,407 - [ERROR] - from application in play-akka.actor.default-dispatcher-1136
    
    
    ! @6mg84abl7 - Internal server error, for (GET) [/resource?set=NWBib&from=275101&size=300] ->
    
    play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
            at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
            at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
            at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
      ...
    Caused by: java.lang.NullPointerException: null
            at models.Hit$2.process(Hit.java:55) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at models.Search.asDocuments(Search.java:318) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at models.Search.doSearch(Search.java:137) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at models.Search.initResults(Search.java:124) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at models.Search.documents(Search.java:110) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at controllers.Application.search(Application.java:123) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at controllers.Api.resource(Api.java:86) ~[lobid.lobid-1.16.0.jar:1.16.0]
            at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:465) ~[lobid.lobid-1.16.0.jar:na]
            at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:465) ~[lobid.lobid-1.16.0.jar:na]
            at play.core.Router$HandlerInvokerFactory$$anon$5.resultCall(Router.scala:267) ~[com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
            at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.11-2.3.4.jar:2.3.4]
    ...

**Comment by dr0i** [comment]
Deployed to production, closing.
